### ISSUE TITLE
Instant crash when starting overwigger

### ISSUE THREAD

**Issue by jorisvdstraten** [brunomolteni/overwigger#1]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/29690384/51745325-bd0c4700-20a2-11e9-8edc-e25fb9c031d5.png">

Process:               overwigger [7976]
Path:                  /private/var/folders/*/overwigger.app/Contents/MacOS/overwigger
Identifier:            io.github.nwjs.overwigger
Version:               0.1.0 (0.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           overwigger [7976]
User ID:               501

Date/Time:             2019-01-25 13:11:04.998 +0100
OS Version:            Mac OS X 10.14.2 (18C54)

**Comment by brunomolteni** [comment]
Hmm I don't have mac so its gonna be hard to debug... Lemme get back to you

**Comment by jorisvdstraten** [comment]
No problem, please let me know if you need more information!

**Comment by brunomolteni** [comment]
Another thing you can try in the meantime, is to install node.js ( any version from 8 up ) and run "node overwigger.server.js" in the app folder, and then navigate to localhost:8888 in the browser...

**Comment by jorisvdstraten** [comment]
Good idea, it works now, thanks!
